ignore = [
    "ANN101",  # Missing type annotation for `self` in method
]
select = [
    "ANN",
    "E",
    "F",
    "FA",
    "W",
]
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FA", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]

line-length = 100

[per-file-ignores]
"tests/*test_*.py" = [
  "ANN",
]

[mccabe]
max-complexity = 10
