from enum import Enum

# https://arxiv.org/category_taxonomy
# cath4s = document.getElementsByTagName("h4")
# a = Array.from(cath4s)
# a.shift()
# strs = a.map(h => `${h.children[0].textContent.replace(/\W/g, "")} = "${h.firstChild.textContent.trim()}"`)
# console.log(strs.join("\n"))

class ComputerScience(Enum):
  ArtificialIntelligence = "cs.AI"
  HardwareArchitecture = "cs.AR"
  ComputationalComplexity = "cs.CC"
  ComputationalEngineeringFinanceAndScience = "cs.CE"
  ComputationalGeometry = "cs.CG"
  ComputationAndLanguage = "cs.CL"
  CryptographyAndSecurity = "cs.CR"
  ComputerVisionAndPatternRecognition = "cs.CV"
  ComputersAndSociety = "cs.CY"
  Databases = "cs.DB"
  DistributedParallelAndClusterComputing = "cs.DC"
  DigitalLibraries = "cs.DL"
  DiscreteMathematics = "cs.DM"
  DataStructuresAndAlgorithms = "cs.DS"
  EmergingTechnologies = "cs.ET"
  FormalLanguagesAndAutomataTheory = "cs.FL"
  GeneralLiterature = "cs.GL"
  Graphics = "cs.GR"
  ComputerScienceAndGameTheory = "cs.GT"
  HumanComputerInteraction = "cs.HC"
  InformationRetrieval = "cs.IR"
  MathInformationTheory = "cs.IT"
  MachineLearning = "cs.LG"
  LogicinComputerScience = "cs.LO"
  MultiagentSystems = "cs.MA"
  Multimedia = "cs.MM"
  MathematicalSoftware = "cs.MS"
  NumericalAnalysis = "cs.NA"
  NeuralAndEvolutionaryComputing = "cs.NE"
  NetworkingAndInternetArchitecture = "cs.NI"
  OtherComputerScience = "cs.OH"
  OperatingSystems = "cs.OS"
  Performance = "cs.PF"
  ProgrammingLanguages = "cs.PL"
  Robotics = "cs.RO"
  SymbolicComputation = "cs.SC"
  Sound = "cs.SD"
  SoftwareEngineering = "cs.SE"
  SocialAndInformationNetworks = "cs.SI"
  SystemsAndControl = "cs.SY"

class Economics(Enum):
  Econometrics = "econ.EM"
  GeneralEconomics = "econ.GN"
  TheoreticalEconomics = "econ.TH"

class ElectricalEngineeringAndSystemsScience(Enum):
  AudioAndSpeechProcessing = "eess.AS"
  ImageAndVideoProcessing = "eess.IV"
  SignalProcessing = "eess.SP"
  SystemsAndControl = "eess.SY"

class Mathematics(Enum):
  CommutativeAlgebra = "math.AC"
  AlgebraicGeometry = "math.AG"
  AnalysisofPDEs = "math.AP"
  AlgebraicTopology = "math.AT"
  ClassicalAnalysisandODEs = "math.CA"
  Combinatorics = "math.CO"
  CategoryTheory = "math.CT"
  ComplexVariables = "math.CV"
  DifferentialGeometry = "math.DG"
  DynamicalSystems = "math.DS"
  FunctionalAnalysis = "math.FA"
  GeneralMathematics = "math.GM"
  GeneralTopology = "math.GN"
  GroupTheory = "math.GR"
  GeometricTopology = "math.GT"
  HistoryandOverview = "math.HO"
  MathInformationTheory = "math.IT"
  KTheoryandHomology = "math.KT"
  Logic = "math.LO"
  MetricGeometry = "math.MG"
  MathematicalPhysics = "math.MP"
  NumericalAnalysis = "math.NA"
  NumberTheory = "math.NT"
  OperatorAlgebras = "math.OA"
  OptimizationandControl = "math.OC"
  Probability = "math.PR"
  QuantumAlgebra = "math.QA"
  RingsandAlgebras = "math.RA"
  RepresentationTheory = "math.RT"
  SymplecticGeometry = "math.SG"
  SpectralTheory = "math.SP"
  StatisticsTheory = "math.ST"

class Physics(Enum):
  CosmologyandNongalacticAstrophysics = "astro-ph.CO"
  EarthandPlanetaryAstrophysics = "astro-ph.EP"
  AstrophysicsofGalaxies = "astro-ph.GA"
  HighEnergyAstrophysicalPhenomena = "astro-ph.HE"
  InstrumentationandMethodsforAstrophysics = "astro-ph.IM"
  SolarandStellarAstrophysics = "astro-ph.SR"
  DisorderedSystemsandNeuralNetworks = "cond-mat.dis-nn"
  MesoscaleandNanoscalePhysics = "cond-mat.mes-hall"
  MaterialsScience = "cond-mat.mtrl-sci"
  OtherCondensedMatter = "cond-mat.other"
  QuantumGases = "cond-mat.quant-gas"
  SoftCondensedMatter = "cond-mat.soft"
  StatisticalMechanics = "cond-mat.stat-mech"
  StronglyCorrelatedElectrons = "cond-mat.str-el"
  Superconductivity = "cond-mat.supr-con"
  GeneralRelativityandQuantumCosmology = "gr-qc"
  HighEnergyPhysicsExperiment = "hep-ex"
  HighEnergyPhysicsLattice = "hep-lat"
  HighEnergyPhysicsPhenomenology = "hep-ph"
  HighEnergyPhysicsTheory = "hep-th"
  MathematicalPhysics = "math-ph"
  AdaptationandSelfOrganizingSystems = "nlin.AO"
  ChaoticDynamics = "nlin.CD"
  CellularAutomataandLatticeGases = "nlin.CG"
  PatternFormationandSolitons = "nlin.PS"
  ExactlySolvableandIntegrableSystems = "nlin.SI"
  NuclearExperiment = "nucl-ex"
  NuclearTheory = "nucl-th"
  AcceleratorPhysics = "physics.acc-ph"
  AtmosphericandOceanicPhysics = "physics.ao-ph"
  AppliedPhysics = "physics.app-ph"
  AtomicandMolecularClusters = "physics.atm-clus"
  AtomicPhysics = "physics.atom-ph"
  BiologicalPhysics = "physics.bio-ph"
  ChemicalPhysics = "physics.chem-ph"
  ClassicalPhysics = "physics.class-ph"
  ComputationalPhysics = "physics.comp-ph"
  DataAnalysisStatisticsandProbability = "physics.data-an"
  PhysicsEducation = "physics.ed-ph"
  FluidDynamics = "physics.flu-dyn"
  GeneralPhysics = "physics.gen-ph"
  Geophysics = "physics.geo-ph"
  HistoryandPhilosophyofPhysics = "physics.hist-ph"
  InstrumentationandDetectors = "physics.ins-det"
  MedicalPhysics = "physics.med-ph"
  Optics = "physics.optics"
  PlasmaPhysics = "physics.plasm-ph"
  PopularPhysics = "physics.pop-ph"
  PhysicsandSociety = "physics.soc-ph"
  SpacePhysics = "physics.space-ph"
  QuantumPhysics = "quant-ph"

class QuantitativeBiology(Enum):
  Biomolecules = "q-bio.BM"
  CellBehavior = "q-bio.CB"
  Genomics = "q-bio.GN"
  MolecularNetworks = "q-bio.MN"
  NeuronsandCognition = "q-bio.NC"
  OtherQuantitativeBiology = "q-bio.OT"
  PopulationsandEvolution = "q-bio.PE"
  QuantitativeMethods = "q-bio.QM"
  SubcellularProcesses = "q-bio.SC"
  TissuesandOrgans = "q-bio.TO"

class QuantitativeFinance(Enum):
  ComputationalFinance = "q-fin.CP"
  Economics = "q-fin.EC"
  GeneralFinance = "q-fin.GN"
  MathematicalFinance = "q-fin.MF"
  PortfolioManagement = "q-fin.PM"
  PricingofSecurities = "q-fin.PR"
  RiskManagement = "q-fin.RM"
  StatisticalFinance = "q-fin.ST"
  TradingandMarketMicrostructure = "q-fin.TR"

class Statistics(Enum):
  Applications = "stat.AP"
  Computation = "stat.CO"
  Methodology = "stat.ME"
  MachineLearning = "stat.ML"
  OtherStatistics = "stat.OT"
  StatisticsTheory = "stat.TH"